### ISSUE TITLE
Sending text message instead of json

### ISSUE THREAD

**Issue by stevezau** [peopledata/fluentd#3]
Hi,

I've opened this issue to discuss the option of sending the data to Sumo in text format rather then json. Many containers long single line messages (such as nginx). It seems unnecessary to attach the json, it also bloats the data costs into sumo.

If we used the metadata (https://github.com/peopledata/fluentd/issues/2) then the text format can be sent but still contain all the information such as POD, Container name etc.

My ruby skills are nonexistent but I think it's similar to how this plugin works

https://github.com/memorycraft/fluent-plugin-sumologic/blob/master/lib/fluent/plugin/out_sumologic.rb#L44

**Comment by Stono** [comment]
Hmmm I'm not entirely sold!  
If we use the metadata plugin, then we'll be sending the body as JSON anyway,  the log data is just one field in that message.

If we don't use the metadata plugin, and send text, and then override the metadata HTTP headers, we're limited to the X-Sumo-* headers that we can send data in.

Take container namespace for example; or replicaset, they don't map to sumo headers, but are important information.

**Comment by stevezau** [comment]
I've already got a prototype working.. I'll open a PR soon
